---
title: "Untitled"
author: "Your Name"
date: "`r format(Sys.Date(), format = '%Y年%m月%d日')`"
output:
  html_document:
    code_folding: show
    df_print: "paged"
    highlight: default
    md_extensions: -ascii_identifiers
    number_sections: no
    theme: lumen
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: no
  ioslides_presentation:
    df_print: paged
    smaller: false
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

require(tidyverse)
```

# 演習１
アンスコムのデータ例（第３回の演習結果）を可視化してください。

```{r}
anscombe
  
```


# 演習２
`iris`データセットを長さと幅の散布図として描いてください。ただし、品種と花弁・がく片で層別してください。

```{r}
iris
  
```


# 演習３
第３回の『メトリクス統計分析入門』の演習問題にある生産性と工数予実割合のヒストグラムを描いてください。ただし、生産性の階級幅は200、工数予実割合の階級幅は0.25とします。

```{r}
"../data/data.csv" %>% 
  readr::read_csv(locale = locale(encoding = "CP932"))
  
```


# 演習４
`iris`データセットを部位と品種で層別した箱ひげ図で描いてください。

```{r}
iris
  
```


# 演習５
第３回の演習５で求めたデータを元にオープン・クローズチャートを描いてください。

```{r}
"../data/redmine_data_utf8.csv" %>% 
  readr::read_csv()

```


---

your signiture and licence