---
title: "第４回データ分析勉強会"
author: "【午前の部/午後の部】再現性のあるレポーティング [鈴木さんぽう, CC BY-NC-SA 4.0]"
date: "`r format(Sys.Date(), format = '%Y年%m月%d日')`"
output:
  ioslides_presentation:
    css: style.css
    df_print: paged
    logo: fig/hex-rmarkdown.png
    smaller: false
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

require(tidyverse)
```


## 本日の内容
1. **再現性のあるレポーティング（午前）**
    * R Markdown概説
    * 演習（テーマ設定）
1. 再現性のあるレポーティング（午後）
    * 演習（レポート作成）
    * 発表

# 再現性のあるレポーティング

## R Markdown概説
* R Markdownとは？
    * Rのコードや**実行結果を文書に埋め込める**Markdown
    * 実行結果をレポートにできる仕組みは**他言語には**ほぼ**ない**
        * 例外：Jupyter Notebook（旧 IPython Notebook）
* Markdownとは？
    * **プレーンテキストで**体裁のある文書を作成するための記法
    * シンプル＆ライトウェイト、テキストなので**VCSで管理可能**
    * 変換ソフト（pandoc）で**多種多様なフォーマット**で出力可能
* [R Markdown Basics](https://k-metrics.github.io/cabinet/communicate/rmd_basics.html)
    * YAML（体裁、出力フォーマットを指定する箇所）
    * Code Chunk（コードを記述する箇所）
    * Markdown（コード以外の文書を記述する箇所）


## 演習（テーマ設定）
* チームごとに何をレポートするかのテーマを設定します
* 設定したテーマに対してR Markdownでレポートを作成します
    * データ（の一部）を変えてレポーティングできるとベスト
    * テーマやデータに対して特に制限は設けません（公序良俗は考えて）
    * フォーマットはHTMLであればドキュメント形式プレゼン形式を問いません

### テーマ例
* 書籍とかには掲載されていない分布表を作ってみる（自由度の高いt分布表）
* デート本、ＳＭ本、統計学基礎の例題や問題を解いてみる
* Redmineチケットや政府統計を可視化したり仮説検定したりしてみる
* K-POPの相関を分析してみる


## チーム分け（仮）

チーム | リーダ | メンバー
-------|--------|-------------
A      | Ka   | 
B      | Fu   | 
C      | Ma   | 
D      | No   | 
E      | Na   | 


## 本日の内容
1. 再現性のあるレポーティング（午前）
    * R Markdown概説
    * レポーティング課題設定
1. **再現性のあるレポーティング（午後）**
    * レポート作成
    * 発表


# 再現性のあるレポーティング

## 演習（レポート作成）

チーム | リーダ | レポートテーマ
-------|--------|-------------
A      | Ka   | 
B      | Fu   | 
C      | Ma   | 
D      | No   | 
E      | Na   | 
　  

* 不明点などは適宜、相談するか質問してください


## 発表

チーム | 発表者 | レポートテーマ
-------|--------|-------------
A      |    | 
B      |    | 
C      |    | 
D      |    | 
E      |    | 


## License

CC BY-NC-SA 4.0, Sampo Suzuki